### ISSUE TITLE
QR Code for Quiz

### ISSUE THREAD

**Issue by Delito1995** [forcedotcom/quiz-host-app#110]
Hello,
I followed all the steps and still not able to have a QR Code to scan and start the game. Anyone could support please ?
Thank you team !
<img width="1061" alt="Capture d’écran 2024-04-20 à 21 25 47" src="https://github.com/forcedotcom/quiz-host-app/assets/167646950/10ee2082-dc0c-4c3b-b4bd-7dc76c119276">

**Comment by pozil** [comment]
Hi @Delito1995, thanks for reporting this issue. The Google library that I used to generate QR code was taken down.
I have replaced it with another library in the latest version of the app.
