### ISSUE TITLE
the application never launches for players - Urgent Please

### ISSUE THREAD

**Issue by Delito1995** [forcedotcom/quiz-host-app#111]
I launch the application and the days have a screen that loads infinitely while on my 'Admin' side I see the questions scrolling and at no time is the game screen displayed for the players. The key is similar between Heroku and Salesforce and the same for the microsite link... I can't find the error, is it a bug? Thank you for your support

**Comment by pozil** [comment]
Hi @Delito1995, it's been some time I haven't run a quiz with the app so I ran a test.
Everything works fine (apart from the QR code issue that your reported) so it must be a configuration issue on your end.

In any case, I have updated the project dependencies so can you pull the latest and give it another try?
Make sure to check the logs for errors (Heroku logs, browser logs and Salesforce logs).
